driver_config:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-west-2
  availability_zone: us-west-2a

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
- name: amazon-2015.09
  driver_config:
    image_id: ami-f0091d91
    instance_type: t2.small
  transport:
    username: ec2-user

- name: redhat-7.2
  driver_config:
    image_id: ami-775e4f16
    instance_type: t2.small
  transport:
    username: ec2-user

- name: ubuntu-12.04
  driver_config:
    image_id: ami-6cb4ae0d
    instance_type: t2.small
  transport:
    username: ubuntu

- name: ubuntu-14.04
  driver_config:
    image_id: ami-22b9a343
    instance_type: t2.small
  transport:
    username: ubuntu

suites:

  - name: ec2_hints
    run_list:
    - recipe[aws::ec2_hints]

  - name: ebs_volume
    run_list:
    - recipe[aws_test::ebs_volume]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: ebs_raid
    run_list:
    - recipe[aws_test::ebs_raid]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: elastic_ip
    run_list:
    - recipe[aws_test::elastic_ip]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        elastic_ip: <%= ENV['AWS_ELASTIC_IP'] %>

  - name: elb
    run_list:
    - recipe[aws_test::elb]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        elb_name: <%= ENV['AWS_ELB_NAME'] %>

  - name: resource_tag
    run_list:
    - recipe[aws_test::resource_tag]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: s3_file
    run_list:
    - recipe[aws_test::s3_file]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        bucket: <%= ENV['AWS_S3_BUCKET'] || 'aws-cookbook' %>
        bucket_west: <%= ENV['AWS_S3_BUCKET_WEST'] || 'aws-cookbook-west' %>
        s3key: <%= ENV['AWS_S3_KEY'] || 'a_file' %>

  - name: instance_monitoring
    run_list:
    - recipe[aws_test::instance_monitoring]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_user
    run_list:
    - recipe[aws_test::iam_user]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_group
    run_list:
    - recipe[aws_test::iam_group]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_role
    run_list:
    - recipe[aws_test::iam_role]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_policy
    run_list:
    - recipe[aws_test::iam_policy]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
