driver_config:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-west-2
  availability_zone: us-west-2a

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
  driver_config:
    image_id: ami-b7a114d7
    instance_type: t2.small
  transport:
    username: ubuntu

suites:
  - name: cfn_stack
    run_list:
    - recipe[aws_test::cfn_stack]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: dynamo_table
    run_list:
    - recipe[aws_test::dynamodb_table]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: ebs_volume
    run_list:
    - recipe[aws_test::ebs_volume]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: elastic_ip
    run_list:
    - recipe[aws_test::elastic_ip]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        elastic_ip: <%= ENV['AWS_ELASTIC_IP'] || '34.208.130.166' %>

  - name: elb
    run_list:
    - recipe[aws_test::elb]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: resource_tag
    run_list:
    - recipe[aws_test::resource_tag]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: s3_file
    run_list:
    - recipe[aws_test::s3_file]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        bucket: <%= ENV['AWS_S3_BUCKET'] || 'aws-cookbook-2' %>
        bucket_west: <%= ENV['AWS_S3_BUCKET_WEST'] || 'aws-cookbook-west' %>
        s3key: <%= ENV['AWS_S3_KEY'] || 'a_file' %>

  - name: instance_monitoring
    run_list:
    - recipe[aws_test::instance_monitoring]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_user
    run_list:
    - recipe[aws_test::iam_user]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_group
    run_list:
    - recipe[aws_test::iam_group]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_role
    run_list:
    - recipe[aws_test::iam_role]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: iam_policy
    run_list:
    - recipe[aws_test::iam_policy]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: cloudwatch_alarm
    run_list:
    - recipe[aws_test::cloudwatch_alarm]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        cloudwatch:
          period: <%= ENV['CLOUDWATCH_PERIOD'] %>
          evaluation_periods: <%= ENV['CLOUDWATCH_EVALUATION_PERIODS'] %>
          threshold: <%= ENV['CLOUDWATCH_THRESHOLD'] %>
          comparison_operator: <%= ENV['CLOUDWATCH_COMPARISON_OPERATOR'] %>
          metric_name: <%= ENV['CLOUDWATCH_METRIC_NAME'] %>
          namespace: <%= ENV['CLOUDWATCH_NAMESPACE'] %>
          statistic: <%= ENV['CLOUDWATCH_STATISTIC'] %>
