source 'https://rubygems.org'

gem 'berkshelf', '>= 4.3'
gem 'chefspec', '~> 4.6'
gem 'cookstyle'
gem 'foodcritic', '~> 7.0'
gem 'kitchen-dokken'
gem 'kitchen-inspec', '>= 0.14'
gem 'kitchen-vagrant', '>= 0.20'
gem 'rake'
gem 'stove'
gem 'test-kitchen', '>= 1.10'
gem 'tomlrb'
gem 'kitchen-ec2'
